package codes.nibby.yi.weiqi

enum class MoveValidationResult {

    OK,
    ERROR_POSITION_OUT_OF_BOUNDS,
    ERROR_INVALID_KO_RECAPTURE,
    ERROR_MOVE_SUICIDAL,
    ERROR_POSITION_REPEAT,
    ERROR_NON_EMPTY_INTERSECTION,
    ERROR_WRONG_STONE_COLOR_THIS_TURN

}