name: Tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests using Gradle
      run: ./gradlew test
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-reports
        path: /home/runner/work/Yi/Yi/build/**/reports/tests/**/*

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Tests using Gradle
        run: ./gradlew testIntegration
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-reports
          path: /home/runner/work/Yi/Yi/build/**/reports/tests/**/*
